theme: minima      # or another theme you are using
title: Project
description:
Hi, I'm Yu-Tang 👋
Data Science and Cognitive Science Student at University of Rochester

Projects
Java Encryption Program
Built encryption/decryption system in Java
Implemented security algorithms
JavaFX Game
Designed GUI game using JavaFX
Implemented game logic and scoring
Data Analysis Project
Tools: Python, R
Performed statistical analysis and visualization
Skills
Python | R | Java | SQL | Linux

Contact
Email: lulu104061@gmail.com LinkedIn: https://www.linkedin.com/in/yu-0a97922b3/
